# Generated by Django 2.0.4 on 2019-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('captcha', models.CharField(max_length=6, verbose_name='验证码')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'captcha',
                'verbose_name_plural': 'captcha',
                'db_table': 'captcha',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('kind', models.CharField(max_length=6, verbose_name='类型')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'phone',
                'verbose_name_plural': 'phone',
                'db_table': 'phone',
                'ordering': ['-id'],
            },
        ),
    ]
