# Generated by Django 2.0.4 on 2019-06-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='status',
        ),
        migrations.AddField(
            model_name='phone',
            name='token',
            field=models.CharField(default='', max_length=64, verbose_name='token'),
            preserve_default=False,
        ),
    ]
